const preset = require('./vendor/filament/filament/tailwind.config.preset')
const path = require('path')

module.exports = {
    presets: [preset],
    content: [
        './app/Filament/**/*.php',
        './resources/views/filament/**/*.blade.php',
        './resources/views/infolists/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
        './resources/js/**/*.{js,jsx}',
        './resources/js/components/**/*.{js,jsx}',
    ],
    corePlugins: {
        preflight: false,
    },
    // Assicurati che Tailwind scansiona anche le classi in template strings
    // Il problema è che Tailwind non scansiona correttamente le classi in template strings multilinea
    // quindi aggiungiamo un safelist completo con pattern per tutte le classi usate
    safelist: [
        // Background colors - pattern semplici
        'bg-white',
        'bg-slate-50',
        'bg-slate-100',
        'bg-slate-800',
        'bg-slate-900',
        'bg-blue-500',
        'bg-blue-600',
        'bg-blue-700',
        'bg-gray-500',
        'bg-gray-600',
        'bg-gray-700',
        'bg-purple-500',
        'bg-orange-500',
        'bg-orange-600',
        'bg-orange-700',
        'bg-green-500',
        'bg-amber-500',
        'bg-red-500',
        // Dark mode backgrounds
        'dark:bg-slate-50',
        'dark:bg-slate-100',
        'dark:bg-slate-700',
        'dark:bg-slate-800',
        'dark:bg-slate-900',
        // Text colors
        'text-white',
        'text-slate-400',
        'text-slate-500',
        'text-slate-600',
        'text-slate-700',
        'text-slate-800',
        'text-slate-900',
        'text-orange-500',
        'text-blue-500',
        'text-blue-600',
        'text-blue-700',
        // Dark mode text
        'dark:text-slate-100',
        'dark:text-slate-200',
        'dark:text-slate-400',
        'dark:text-slate-500',
        'dark:text-slate-600',
        'dark:text-slate-700',
        'dark:text-slate-800',
        'dark:text-slate-900',
        // Border colors
        'border-slate-200',
        'border-slate-300',
        'border-slate-500',
        'border-slate-700',
        'border-slate-800',
        'border-blue-500',
        'border-blue-700',
        'border-gray-500',
        'border-gray-700',
        'border-orange-500',
        'border-orange-700',
        // Dark mode borders
        'dark:border-slate-200',
        'dark:border-slate-300',
        'dark:border-slate-500',
        'dark:border-slate-700',
        'dark:border-slate-800',
        'dark:border-blue-500',
        'dark:border-blue-700',
        'dark:border-gray-500',
        'dark:border-gray-700',
        'dark:border-orange-500',
        'dark:border-orange-700',
        // Border radius
        'rounded-md',
        'rounded-xl',
        // Shadows
        'shadow-md',
        'shadow-lg',
        // Gradients
        'bg-gradient-to-r',
        'from-blue-600',
        'to-blue-700',
        'from-gray-600',
        'to-gray-700',
        'from-orange-500',
        'to-orange-700',
        // Spacing utilities
        'p-2',
        'p-3',
        'p-4',
        'px-2',
        'px-3',
        'px-4',
        'py-1',
        'py-2',
        'py-2.5',
        'm-2',
        'm-3',
        'mt-1',
        'mt-3',
        'mb-2',
        'mb-3',
        'ml-2',
        'gap-1.5',
        'gap-2',
        'gap-3',
        // Sizes
        'w-2.5',
        'w-3',
        'w-3.5',
        'w-4',
        'w-full',
        'h-2.5',
        'h-3',
        'h-3.5',
        'h-4',
        // Flexbox
        'flex',
        'flex-col',
        'items-center',
        'justify-between',
        'justify-end',
        'flex-wrap',
        // Other utilities
        'box-border',
        'overflow-hidden',
        'transition-colors',
        'transition-opacity',
        'transition-transform',
        'cursor-pointer',
        'uppercase',
        'font-bold',
        'font-medium',
        'font-semibold',
        'tracking-wider',
        'leading-snug',
        'leading-relaxed',
        'line-clamp-2',
        'text-ellipsis',
        'whitespace-nowrap',
        'opacity-0',
        'hover:opacity-90',
        'hover:text-white',
        'focus:border-orange-500',
        'dark:focus:border-orange-500',
        // Arbitrary values
        'min-w-[240px]',
        'min-w-[280px]',
        'min-w-[300px]',
        'max-w-[280px]',
        'max-w-[320px]',
        'max-w-[400px]',
        'text-[10px]',
        'text-[11px]',
        'text-[13px]',
        'text-[15px]',
        '-left-[5px]',
        '-right-[5px]',
    ],
}
