<?php

namespace Voodflow\Voodflow\Nodes\FilterProNode;

use Voodflow\Voodflow\Contracts\NodeInterface;

/**
 * FilterPro Node Handler
 * 
 * Type: filter
 * Description: Filter data based on complex conditions
 * 
 * Generated by: php artisan signal:make-node
 */
class FilterProNode implements NodeInterface
{
    /**
     * The node type identifier
     */
    public static function type(): string
    {
        return 'filter_pro';
    }

    /**
     * Get the node name
     */
    public static function name(): string
    {
        return 'FilterPro';
    }

    /**
     * Get the default configuration for this node
     */
    public static function defaultConfig(): array
    {
        return [
            'label' => 'FilterPro',
            'description' => 'Filter data based on complex conditions',
            // Add your default config here
        ];
    }

    /**
     * Get node metadata
     */
    public static function metadata(): array
    {
        return [
            'author' => 'Voodflow',
            'version' => '1.0.0',
            'category' => 'transform',
            'description' => 'Advanced filtering with complex conditions',
            'color' => 'purple',
            'icon' => 'heroicon-o-filter',
            'group' => 'Filters',
            'positioning' => [
                'input' => true,
                'output' => true,
            ],
        ];
    }

    /**
     * Execute filter logic with new signature
     */
    public function execute(\Voodflow\Voodflow\Execution\ExecutionContext $context): \Voodflow\Voodflow\Execution\ExecutionResult
    {
        // Pass through for now - filtering logic not yet implemented
        return \Voodflow\Voodflow\Execution\ExecutionResult::success($context->input);
    }

    /**
     * Validate the node configuration
     * 
     * @param array $config The node configuration
     * @return array Array of validation errors, empty if valid
     */
    public function validate(array $config): array
    {
        $errors = [];

        // TODO: Add your validation logic here
        // Example:
        // if (empty($config['required_field'])) {
        //     $errors[] = 'Required field is missing';
        // }

        return $errors;
    }
}