<?php

namespace Voodflow\Voodflow\Nodes;

use Voodflow\Voodflow\Contracts\NodeInterface;

/**
 * FilterPro Node Handler
 *
 * Type: filter
 * Description: Filter data based on complex conditions
 *
 * Generated by: php artisan signal:make-node
 */
class FilterProNode implements NodeInterface
{
    /**
     * The node type identifier
     */
    public static function type(): string
    {
        return 'base33_filter_pro';
    }

    /**
     * Get the node name
     */
    public static function name(): string
    {
        return 'FilterPro';
    }

    /**
     * Get the default configuration for this node
     */
    public static function defaultConfig(): array
    {
        return [
            'label' => 'FilterPro',
            'description' => 'Filter data based on complex conditions',
            // Add your default config here
        ];
    }

    /**
     * Get node metadata
     */
    public static function metadata(): array
    {
        return [
            'author' => 'Base33',
            'version' => '1.0.0',
            'color' => 'purple',
            'icon' => 'heroicon-o-filter',
            'group' => 'Filters',
            'positioning' => [
                'input' => true,
                'output' => true,
            ],
        ];
    }

    /**
     * Execute the node logic
     *
     * @param  array  $input  The input data from previous nodes
     * @param  array  $config  The node configuration
     * @return array The output data to pass to next nodes
     */
    public function execute(array $input, array $config): array
    {
        // TODO: Implement your node logic here

        // Example:
        // $result = $this->doSomething($input, $config);
        // return ['success' => true, 'data' => $result];

        return $input;
    }

    /**
     * Validate the node configuration
     *
     * @param  array  $config  The node configuration
     * @return array Array of validation errors, empty if valid
     */
    public function validate(array $config): array
    {
        $errors = [];

        // TODO: Add your validation logic here
        // Example:
        // if (empty($config['required_field'])) {
        //     $errors[] = 'Required field is missing';
        // }

        return $errors;
    }
}
