<?php

namespace Voodflow\Voodflow\Nodes;

use Voodflow\Voodflow\Contracts\NodeInterface;

/**
 * SendWebhook Node Handler
 * 
 * Type: action
 * Description: Send webhook
 * 
 * Generated by: php artisan signal:make-node
 */
class SendWebhookNode implements NodeInterface
{
    /**
     * The node type identifier
     */
    public static function type(): string
    {
        return 'base33_send_webhook';
    }

    /**
     * Get the node name
     */
    public static function name(): string
    {
        return 'SendWebhook';
    }

    /**
     * Get the default configuration for this node
     */
    /**
     * Get the default configuration for this node
     */
    public static function defaultConfig(): array
    {
        return [
            'label' => 'SendWebhook',
            'description' => '',
            // Add your default config here
        ];
    }

    /**
     * Get node metadata
     */
    public static function metadata(): array
    {
        return [
            'author' => 'Base33',
            'version' => '1.0.0',
            'color' => 'blue',
            'icon' => 'heroicon-o-paper-airplane',
            'group' => 'Actions',
            'positioning' => [
                'input' => true,
                'output' => true, // Can act as pass-through
            ],
        ];
    }

    /**
     * Execute the node logic
     * 
     * @param array $input The input data from previous nodes
     * @param array $config The node configuration
     * @return array The output data to pass to next nodes
     */
    public function execute(array $input, array $config): array
    {
        // TODO: Implement actual webhook sending
        // 1. Get Http client
        // 2. Build payload from input based on config['fields']
        // 3. Send request to config['url'] with config['method']
        // 4. Return ['success' => true/false] to determine next branch
        
        return $input;
    }

    /**
     * Validate the node configuration
     * 
     * @param array $config The node configuration
     * @return array Array of validation errors, empty if valid
     */
    public function validate(array $config): array
    {
        $errors = [];
        
        // Check required fields
        if (empty($config['url'])) {
            $errors[] = 'URL is required';
        }

        if (empty($config['method'])) {
            $errors[] = 'HTTP Method is required';
        }
        
        return $errors;
    }
}