<?php

namespace Base33\FilamentSignal\Nodes;

use Base33\FilamentSignal\Contracts\NodeInterface;

/**
 * SendWebhook Node Handler
 * 
 * Type: action
 * Description: Send webhook
 * 
 * Generated by: php artisan signal:make-node
 */
class SendWebhookNode implements NodeInterface
{
    /**
     * The node type identifier
     */
    public static function type(): string
    {
        return 'action';
    }

    /**
     * Get the node name
     */
    public static function name(): string
    {
        return 'SendWebhook';
    }

    /**
     * Get the default configuration for this node
     */
    /**
     * Get the default configuration for this node
     */
    public static function defaultConfig(): array
    {
        return [
            'label' => 'SendWebhook',
            'description' => '',
            // Add your default config here
        ];
    }

    /**
     * Get node metadata
     */
    public static function metadata(): array
    {
        return [
            'author' => 'Base33',
            'version' => '1.0.0',
            'color' => 'blue',
            'icon' => 'heroicon-o-paper-airplane',
            'group' => 'Actions',
            'positioning' => [
                'input' => true,
                'output' => true, // Can act as pass-through
            ],
        ];
    }

    /**
     * Execute the node logic
     * 
     * @param array $input The input data from previous nodes
     * @param array $config The node configuration
     * @return array The output data to pass to next nodes
     */
    public function execute(array $input, array $config): array
    {
        // TODO: Implement your node logic here
        
        // Example:
        // $result = $this->doSomething($input, $config);
        // return ['success' => true, 'data' => $result];
        
        return $input;
    }

    /**
     * Validate the node configuration
     * 
     * @param array $config The node configuration
     * @return array Array of validation errors, empty if valid
     */
    public function validate(array $config): array
    {
        $errors = [];
        
        // TODO: Add your validation logic here
        // Example:
        // if (empty($config['required_field'])) {
        //     $errors[] = 'Required field is missing';
        // }
        
        return $errors;
    }
}