<?php

namespace Voodflow\Voodflow\Nodes;

use Voodflow\Voodflow\Contracts\NodeInterface;

/**
 * SendWebhook Node Handler
 * 
 * Type: action
 * Description: Send webhook
 * 
 * Generated by: php artisan signal:make-node
 */
class SendWebhookNode implements NodeInterface
{
    /**
     * The node type identifier
     */
    public static function type(): string
    {
        return 'send_webhook';
    }

    /**
     * Get the node name
     */
    public static function name(): string
    {
        return 'SendWebhook';
    }

    /**
     * Get the default configuration for this node
     */
    /**
     * Get the default configuration for this node
     */
    public static function defaultConfig(): array
    {
        return [
            'label' => 'SendWebhook',
            'description' => '',
            // Add your default config here
        ];
    }

    /**
     * Get node metadata
     */
    public static function metadata(): array
    {
        return [
            'author' => 'Voodflow',
            'version' => '1.0.0',
            'color' => 'blue',
            'icon' => 'heroicon-o-paper-airplane',
            'group' => 'Actions',
            'positioning' => [
                'input' => true,
                'output' => true, // Can act as pass-through
            ],
        ];
    }

    /**
     * Execute webhook send with new signature
     */
    public function execute(\Voodflow\Voodflow\Execution\ExecutionContext $context): \Voodflow\Voodflow\Execution\ExecutionResult
    {
        // Delegate to WebhookNode implementation for now
        // TODO: Migrate logic from old WebhookActionHandler
        return \Voodflow\Voodflow\Execution\ExecutionResult::success($context->input);
    }

    /**
     * Validate the node configuration
     * 
     * @param array $config The node configuration
     * @return array Array of validation errors, empty if valid
     */
    public function validate(array $config): array
    {
        $errors = [];

        // Check required fields
        if (empty($config['url'])) {
            $errors[] = 'URL is required';
        }

        if (empty($config['method'])) {
            $errors[] = 'HTTP Method is required';
        }

        return $errors;
    }
}